webapp:
  image:
    repository: ghcr.io/ever-co/gauzy-webapp
    tag: "latest"

  env:
    production: true

  baseUrls:
    api: "https://apiprod.gauzy.co"
    client: "https://prod.gauzy.co"

  cloudinary:
    apiKey: "256868982483961"
    cloudName: "dv6ezkfxg"

  googleMap:
    apiKey: "AIzaSyCJmnKzgTSq5Pc93HXar5bZrdmANTwtSIo"
    defaultLatitude: "42.6459136"
    defaultLongitude: "23.3332736"

  ingress:
    enabled: true
    className: "nginx"
    annotations: 
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: prod.gauzy.co
        paths:
          - path: /
            pathType: Prefix
    # tls:
    #  - secretName: chart-example-tls
    #    hosts:
    #      - prod.gauzy.co
  envs:
    - name: SENTRY_DSN
      value: "https://7cd381188b6f446ca0e69185227b9031@o51327.ingest.sentry.io/4397292"
    - name: CHATWOOT_SDK_TOKEN
      value: "fPgSSzSQoAWRuDqYyNXmpGLM"

ever-gauzy-api:
  global:
    env:
      production: true
    baseUrls:
      api: "https://apiprod.gauzy.co"
      client: "https://prod.gauzy.co"
  image:
    repository: ghcr.io/ever-co/gauzy-api
    tag: "latest"
  loglevel: "info"
  adminPasswordReset: true
  sentry:
    sentryDsn: "https://7cd381188b6f446ca0e69185227b9031@o51327.ingest.sentry.io/4397292"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: apiprod.gauzy.co
        paths:
          - path: /
            pathType: Prefix
    # tls:
    #  - secretName: chart-example-tls
    #    hosts:
    #      - apiprod.gauzy.co
  envs:
    - name: EXPRESS_SESSION_SECRET
      value: "gauzy"
    - name: DB_SSL_MODE
      value: "disable"
    - name: DB_CA_CERT
      value: ""
    - name: DB_URI
      value: ""
    - name: DB_TYPE
      value: "postgres"
  postgresql:
    global:
      storageClass: "nfs-client"
      postgresql:
        auth:
          postgresPassword: "postgres"
          username: "gauzy"
          password: "gauzy"
          database: "gauzy"
