apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api.labels" . | nindent 8 }}
	{{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          env:
            {{- with .Values.api.envs }}
            {{- . | toYaml | trim | nindent 12 }}
            {{- end }}
            - name: DEMO
              value: {{ include "ever-gauzy.demoenv" . | quote }}
            - name: API_HOST
              value: 0.0.0.0
            - name: NODE_ENV
              value: {{ include "ever-gauzy.nodeenv" . | quote }}
            - name: API_BASE_URL
              value: {{ .Values.global.baseUrls.api | quote }}
            - name: CLIENT_BASE_URL
              value: {{ .Values.global.baseUrls.client | quote }}
            - name: ADMIN_PASSWORD_RESET
              value: {{ .Values.api.adminPasswordReset | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.api.loglevel | quote }}
            - name: SENTRY_DSN
              value: {{ .Values.api.sentry.sentryDsn | quote }}
            - name: SENTRY_HTTP_TRACING_ENABLED
              value: {{ .Values.api.sentry.sentryHttpTracingEnabled | quote }}
            - name: SENTRY_POSTGRES_TRACKING_ENABLED
              value: {{ .Values.api.sentry.sentryPostgresTrackingEnabled | quote }}
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: DB_USER
              value: {{ .Values.postgresql.global.postgresql.auth.username | quote }}
            - name: DB_PASS
              value: {{ .Values.postgresql.global.postgresql.auth.password | quote }}
            - name: DB_NAME
              value: {{ .Values.postgresql.global.postgresql.auth.database | quote }}
            - name: DB_PORT
              value: {{ include "postgresql.servicePort" .Values.postgresql.global.postgresql.service.ports.postgresql | quote }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.api.s3.awsAccessKeyId | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.api.s3.awsSecretAccessKey | quote }}
            - name: AWS_REGION
              value: {{ .Values.api.s3.awsRegion | quote }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.api.s3.awsS3Bucket | quote }}
            - name: WASABI_ACCESS_KEY_ID
              value: {{ .Values.api.wasabi-s3.wasabiAccessKeyId | quote }}
            - name: WASABI_SECRET_ACCESS_KEY
              value: {{ .Values.api.wasabi-s3.wasabiSecretAccessKey | quote }}
            - name: WASABI_REGION
              value: {{ .Values.api.wasabi-s3.wasabiRegion | quote }}
            - name: WASABI_SERVICE_URL
              value: {{ .Values.api.wasabi-s3.wasabiServiceUrl | quote }}
            - name: WASABI_S3_BUCKET
              value: {{ .Values.api.wasabi-s3.wasabiServiceUrl | quote }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
