ever-teams:
  global:
    env:
      production: false

  image:
    repository: ghcr.io/ever-co/ever-teams-webapp
    tag: "latest"

  envs:
    - name: NEXT_PUBLIC_COOKIE_DOMAINS
      value: "ever.team"

  gauzy:
    gauzyApiServerUrl: "https://apidemo.gauzy.co"
    nextPublicGauzyApiServerUrl: "https://apidemo.gauzy.co/api"

  sentry:
    sentryProject: "ever-teams-web"
    sentryDebug: "false"
    sentryOrg: "ever-co"

  smtp:
    smtpFromAddress: noreply@ever.team"

  board:
    nextPublicBoardBackendPostUrl: "https://jsonboard.ever.team/api/v2/post/"
    nextPublicBoardAppDomain: "https://board.ever.team"

  meet:
    meetJwtAppId: "ever_teams"
    nextPublicMeetDomain: "meet.ever.team"

  ingress:
    enabled: true
    className: "nginx"
    annotations: 
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: demo.ever.team
        paths:
          - path: /
            pathType: Prefix
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
ever-gauzy-api:
  global:
    env:
      production: false
    baseUrls:
      api: "https://apidemo.gauzy.co"
      client: "https://demo.gauzy.co"
  loglevel: "info"
  adminPasswordReset: true
  sentry:
    sentryDsn: "https://7cd381188b6f446ca0e69185227b9031@o51327.ingest.sentry.io/4397292"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: apidemo.gauzy.co
        paths:
          - path: /
            pathType: Prefix
    # tls:
    #  - secretName: chart-example-tls
    #    hosts:
    #      - apidemo.gauzy.co
  envs:
    - name: EXPRESS_SESSION_SECRET
      value: "gauzy"

