apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      {{- include "webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.webapp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webapp.labels" . | nindent 8 }}
	{{- with .Values.webapp.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.webapp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      serviceAccountName: {{ include "webapp.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.webapp.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-webapp
          securityContext:
            {{- toYaml .Values.webapp.securityContext | nindent 12 }}
          image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag | default .Chart.AppVersion }}"
          env:
            {{- with .Values.webapp.envs }}
            {{- . | toYaml | trim | nindent 12 }}
            {{- end }}
            - name: DEMO
              value: {{ include "ever-gauzy.demoenv" . | quote }}
            - name: API_BASE_URL
              value: {{ .Values.global.baseUrls.api | quote }}
            - name: CLIENT_BASE_URL
              value: {{ .Values.global.baseUrls.client | quote }}
            - name: CLOUDINARY_API_KEY
              value: {{ .Values.webapp.cloudinary.apiKey | quote }}
            - name: CLOUDINARY_CLOUD_NAME
              value: {{ .Values.webapp.cloudinary.cloudName | quote }}
            - name: GOOGLE_MAPS_API_KEY
              value: {{ .Values.webapp.googleMap.apiKey | quote }}
            - name: GOOGLE_PLACE_AUTOCOMPLETE
              value: {{ .Values.webapp.googleMap.autoComplete | quote }}
            - name: DEFAULT_LATITUDE
              value: {{ .Values.webapp.googleMap.defaultLatitude | quote }}
            - name: DEFAULT_LONGITUDE
              value: {{ .Values.webapp.googleMap.defaultLongitude | quote }}
            - name: DEFAULT_CURRENCY
              value: {{ .Values.webapp.googleMap.defaultCurrency | quote }}
            - name: GAUZY_GITHUB_CLIENT_ID
              value: {{ .Values.webapp.gitHub.clientId | quote }}
            - name: GAUZY_GITHUB_APP_NAME
              value: {{ .Values.webapp.gitHub.appName | quote }}
            - name: GAUZY_GITHUB_REDIRECT_URL
              value: {{ .Values.webapp.gitHub.redirectUrl | quote }}
            - name: GAUZY_GITHUB_POST_INSTALL_URL
              value: {{ .Values.webapp.gitHub.postInstallUrl | quote }}
            - name: GAUZY_GITHUB_APP_ID
              value: {{ .Values.webapp.gitHub.appId | quote }}
            - name: JITSU_BROWSER_URL
              value: {{ .Values.webapp.jitsu.browserUrl | quote }}
            - name: JITSU_BROWSER_WRITE_KEY
              value: {{ .Values.webapp.jitsu.browserWriteKey | quote }}
          imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webapp.service.targetPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.webapp.resources | nindent 12 }}
      {{- with .Values.webapp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webapp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webapp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
